apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slink-archive
  labels:
    app.kubernetes.io/component: archive
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
