"""add victim_hash to detections

Revision ID: 4db5d683f263
Revises: 0bcb98531af3
Create Date: 2026-03-25 11:02:06.194136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db5d683f263'
down_revision: Union[str, Sequence[str], None] = '0bcb98531af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('victim_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_detections_victim_hash'), 'detections', ['victim_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_victim_hash'), table_name='detections')
    op.drop_column('detections', 'victim_hash')
    # ### end Alembic commands ###
