"""initial schema

Revision ID: b242d0d6700b
Revises: 
Create Date: 2026-03-24 16:34:10.004426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b242d0d6700b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('matched_keywords', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_content_hash'), 'detections', ['content_hash'], unique=True)
    op.create_index(op.f('ix_detections_severity'), 'detections', ['severity'], unique=False)
    op.create_index(op.f('ix_detections_source'), 'detections', ['source'], unique=False)
    op.create_index(op.f('ix_detections_status'), 'detections', ['status'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_term'), 'keywords', ['term'], unique=False)
    op.create_table('source_status',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('last_poll', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_status')
    op.drop_index(op.f('ix_keywords_term'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_detections_status'), table_name='detections')
    op.drop_index(op.f('ix_detections_source'), table_name='detections')
    op.drop_index(op.f('ix_detections_severity'), table_name='detections')
    op.drop_index(op.f('ix_detections_content_hash'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
